CleanBookLibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls', namespace='slug')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.conf.urls import re_path
from .views import (
    BookList,
    BookDetails,
    SingleCategoryView,
    SingleAuthorView,
    SingleLanguage,
    #AuthorDetailsView,
)

app_name = 'library'

urlpatterns = [
    re_path('^$', BookList.as_view(), name='book_list'),
    re_path('books/(?P<slug>[-\w]+)', BookDetails.as_view(), name='book_details'),
    re_path('category/(?P<slug>[-\w]+)', SingleCategoryView.as_view(), name='single_category_details'),
    re_path('author/(?P<slug>[-\w]+)', SingleAuthorView.as_view(), name='single_author_details'),
    re_path('language/(?P<slug>[-\w]+)', SingleLanguage.as_view(), name='single_language_list'),
    #re_path('author-detail/', AuthorDetailsView.as_view(), name='author_detail_view'),
]

library/models.py
import uuid
from django.db import models
from django.urls import reverse
#from django.utils.text import slugify


class EntryQuerySet(models.QuerySet):
    def published(self):
        return self.filter(publish=True)


class Category(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book Category (e.g. Science Fiction)')
    slug = models.SlugField()

    # def save(self, *args, **kwargs):
    #     # Uncomment if you don't want the slug to change every time the name changes
    #     # if self.id is None:
    #     # self.slug = slugify(self.name)
    #     self.slug = slugify(self.name)
    #     super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Currency(models.Model):
    currency = models.CharField(max_length=10)
    slug = models.SlugField()

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.currency)
    #     super(Currency, self).save(*args, **kwargs)

    def __str__(self):
        return self.currency


class Language(models.Model):
    language = models.CharField(max_length=50)
    slug = models.SlugField()

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.language)
    #     super(Language, self).save(*args, **kwargs)

    def __str__(self):
        return self.language


class Editor(models.Model):
    editor = models.CharField(max_length=190)
    slug = models.SlugField()

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.editor)
    #     super(Editor, self).save(*args, **kwargs)

    def __str__(self):
        return self.editor


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    slug = models.SlugField()

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.first_name, self.last_name)
    #     super(Author, self).save(*args, **kwargs)

    class Meta:
        ordering = ['last_name', 'first_name']

    # def get_absolute_url(self):
    #     """Returns the url to access a particular author instance."""
    #     return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Book(models.Model):
    name_of_the_book = models.CharField(max_length=200)
    edition = models.CharField(max_length=13)
    author = models.ManyToManyField(Author, help_text='Select Author name')
    editor = models.ManyToManyField(Editor, help_text='Select Editor name')
    translator = models.ManyToManyField(Language, related_name='languages', help_text='Select Language')
    publisher = models.CharField(max_length=255)
    place = models.CharField(max_length=190)
    month = models.CharField(max_length=20)
    year = models.IntegerField()
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
                            blank=True, null=True)
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE)
    price = models.IntegerField()
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category, help_text='Select category for this book')
    pages = models.IntegerField()
    copy = models.PositiveSmallIntegerField(blank=True, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    image = models.ImageField(upload_to='book_photos/', blank=True, null=True)
    published = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField()
    publish = models.BooleanField(default=True)
    objects = EntryQuerySet.as_manager()

    class Meta:
        ordering = ["-published"]

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.name_of_the_book)
    #     super(Book, self).save(*args, **kwargs)

    def __str__(self):
        return self.name_of_the_book

    # def get_absolute_url(self):
    #     return "/book_list/%s/" %(self.id)

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book_details', args=[str(self.id)])


# Declare the ForeignKey with related_query_name
class Tag(models.Model):
    article = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
        related_name="tags",
        related_query_name="tag",
    )
    name = models.CharField(max_length=255)
    slug = models.SlugField()

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.name)
    #     super(Tag, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    slug = models.SlugField()

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.imprint)
    #     super(BookInstance, self).save(*args, **kwargs)

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return f'{self.id} ({self.book.name_of_the_book})'

templates/books/author.html
{% extends "books/base.html" %}

{% block content %}
    <h2>Author {{ object_list }}</h2>

    <ol>
      {% for book in page_obj %}
        <li>{{ book.name_of_the_book }}</li>
      {% endfor %}
    </ol>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

templates/books/backup.html
<!-- nav bar -->
<div class="navbar">

  <a href="{% url 'book_list' %}">Home</a>
  <div class="dropdown">
    <button class="dropbtn">Category
      <i class="fa fa-caret-down"></i>
    </button>

    <div class="dropdown-content">
        {% for object in category_list %}
       <a href="{% url 'single_category_details' object.pk %}">{{ object.name }}</a>
        {% endfor %}
    </div>
  </div>

  <div class="dropdown">
    <button class="dropbtn">Author
      <i class="fa fa-caret-down"></i>
    </button>

    <div class="dropdown-content">
        {% for object in author_list %}
       <a href="{% url 'single_author_details' object.pk %}">{{ object.first_name }} {{ object.last_name }}</a>
        {% endfor %}
    </div>
  </div>

  <div class="dropdown">
    <button class="dropbtn">Language
      <i class="fa fa-caret-down"></i>
    </button>

    <div class="dropdown-content">
        {% for object in language_list %}
       <a href="{% url 'single_language_list' object.pk %}">{{ object.language }}</a>
        {% endfor %}
    </div>
  </div>

</div>
<!-- nav bar end -->

templates/books/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}

    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        body {
          font-family: Arial;
        }

        * {
          box-sizing: border-box;
        }

        form.example input[type=text] {
          padding: 10px;
          font-size: 17px;
          border: 1px solid grey;
          float: left;
          width: 80%;
          background: #f1f1f1;
        }

        form.example button {
          float: left;
          width: 20%;
          padding: 10px;
          background: #2196F3;
          color: white;
          font-size: 17px;
          border: 1px solid grey;
          border-left: none;
          cursor: pointer;
        }

        form.example button:hover {
          background: #0b7dda;
        }

        form.example::after {
          content: "";
          clear: both;
          display: table;
        }

         /* Navbar container */
        .navbar {
          overflow: hidden;
          background-color: #333;
          font-family: Arial;
        }

        /* Links inside the navbar */
        .navbar a {
          float: left;
          font-size: 16px;
          color: white;
          text-align: center;
          padding: 14px 16px;
          text-decoration: none;
        }

        /* The dropdown container */
        .dropdown {
          float: left;
          overflow: hidden;
        }

        /* Dropdown button */
        .dropdown .dropbtn {
          font-size: 16px;
          border: none;
          outline: none;
          color: white;
          padding: 14px 16px;
          background-color: inherit;
          font-family: inherit; /* Important for vertical align on mobile phones */
          margin: 0; /* Important for vertical align on mobile phones */
        }

        /* Add a red background color to navbar links on hover */
        .navbar a:hover, .dropdown:hover .dropbtn {
          background-color: red;
        }

        /* Dropdown content (hidden by default) */
        .dropdown-content {
          display: none;
          position: absolute;
          background-color: #f9f9f9;
          min-width: 160px;
          box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
          z-index: 1;
        }

        /* Links inside the dropdown */
        .dropdown-content a {
          float: none;
          color: black;
          padding: 12px 16px;
          text-decoration: none;
          display: block;
          text-align: left;
        }

        /* Add a grey background color to dropdown links on hover */
        .dropdown-content a:hover {
          background-color: #ddd;
        }

        /* Show the dropdown menu on hover */
        .dropdown:hover .dropdown-content {
          display: block;
        }

     </style>
</head>
<body>

<!-- nav bar -->
<div class="navbar">

  <a href="{% url 'library:book_list' %}">Home</a>
  <div class="dropdown">
    <button class="dropbtn">Category
      <i class="fa fa-caret-down"></i>
    </button>

    <div class="dropdown-content">
        {% for object in category_list %}
       <a href="{% url 'library:single_category_details' object.slug %}">{{ object.name }}</a>
        {% endfor %}
    </div>
  </div>

  <div class="dropdown">
    <button class="dropbtn">Author
      <i class="fa fa-caret-down"></i>
    </button>

    <div class="dropdown-content">
        {% for object in author_list %}
       <a href="{% url 'library:single_author_details' object.slug %}">{{ object.first_name }} {{ object.last_name }}</a>
        {% endfor %}
    </div>
  </div>

  <div class="dropdown">
    <button class="dropbtn">Language
      <i class="fa fa-caret-down"></i>
    </button>

    <div class="dropdown-content">
        {% for object in language_list %}
       <a href="{% url 'library:single_language_list' object.slug %}">{{ object.language }}</a>
        {% endfor %}
    </div>
  </div>

</div>
<!-- nav bar end -->

<br>
<form class="example" action="{% url 'library:book_list' %}" style="margin:auto;max-width:300px">
  <input type="text" name='q' placeholder="Search...">
  <button type="submit" value='{{ request.GET.q }}'><i class="fa fa-search"></i></button>
</form><br>

{% block content %}

{% endblock %}


</body>
</html>

templates/books/book_details.html
{% extends 'books/base.html' %}
{% block title %}<title>{{ object.name_of_the_book }}</title>{% endblock %}
{% block content %}

    <div style="padding-left: 39%">
        <p><img src="{{ MEDIA_URL }}{{ object.image.url }}" style="width: 350px;height: 400px"></p>
        <p style="color: #06a019; font-size: 30px"><span>বইয়ের নাম:</span> {{ object.name_of_the_book }}</p>
        <p style="color: #06a019; font-size: 30px"><span>ISBN:</span> {{ object.isbn }}</p>
        <p style="color: #06a019; font-size: 30px"><span>অনুবাদক:</span> {% for translation in object.translation.all %} {{ translation }}<br> {% endfor %}</p>
        <p style="color: #06a019; font-size: 30px"><span>সংস্করণ:</span> {{ object.edition }}</p>
        <p style="color: #06a019; font-size: 30px"><span>Editor:</span> {{ object.editor }}</p>
        <p style="color: #06a019; font-size: 30px"><span>Place:</span> {{ object.place }}</p>
        <p style="color: #06a019; font-size: 30px"><span>Pages:</span> {{ object.pages }}</p>
        <p style="color: #06a019; font-size: 30px"><span>Language:</span> {{ object.language }}</p>
        <p style="color: #06a019; font-size: 30px"><span>Publisher:</span> {{ object.publisher }}</p>
        <p style="color: #06a019; font-size: 30px"><span>Author:</span> {% for author in object.author.all %} {{ author }} <br> {% endfor %}</p>
        <p style="color: #11a06c"><span>Summary:</span> {{ object.summary }}</p>
        <p style="color: #06a019; font-size: 30px"><span>Category:</span> {% for category in object.category.all %} {{ category }} <br> {% endfor %}</p>
        <p style="color: #06a019; font-size: 30px"><span>Published:</span> {{ object.published }}</p>
        <p><span>Added This Book</span> {{ object.published|timesince }} <span>ago</span></p>
        {% load tz %}
        {% localtime on %}
            <p><span>Todays Date:</span> {{ now|date }} {{ now|time }}</p>
        {% endlocaltime %}
    </div>

{% endblock %}

templates/books/book_lists.html
{% extends 'books/base.html' %}
{% block title %}<title>Home</title>{% endblock %}
{% block content %}

    <section class="blog-area section">
		<div class="container">

			<div class="row">

                {% for object in object_list %}

				<div class="col-lg-4 col-md-6">
					<div class="card h-100">
						<div class="single-post post-style-1">

							<div class="blog-info">

								<a href="{% url 'library:book_details' slug=object.slug %}"><img src="{{ MEDIA_URL }}{{ object.image.url }}" style="width: 150px;height: 200px"></a>
                                    {{ object.name_of_the_book }}

							</div><!-- blog-info -->
						</div><!-- single-post -->
					</div><!-- card -->
				</div><!-- col-lg-4 col-md-6 -->

                {% endfor %}

			</div><!-- row -->

        <!-- 9. EXTRA SMALL BLOG -->

            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}" style="color: #13b521">Previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}" style="color: #13b521">Next</a>
                    {% endif %}
                </span>
            </div>

		</div><!-- container -->
	</section><!-- section -->

{% endblock %}

templates/books/single_author.html
{% extends 'books/base.html' %}
{% block title %}<title>{{ object.first_name }} {{ object.last_name }}</title>{% endblock %}
{% block content %}

<h3>{{ object.first_name }} {{ object.last_name }}</h3>

    {% for book in object.book_set.all %} <a href="{% url 'library:book_details' book.slug %}"><img src="{{ MEDIA_URL }}{{ book.image.url }}" style="width: 150px;height: 200px"> {{ book }}</a> <br>{% endfor %}<br>

    Total Book: {{ object.book_set.count }}

{% endblock %}

templates/books/single_category.html
{% extends 'books/base.html' %}
{% block title %}<title>{{ object.name }}</title>{% endblock %}
{% block content %}

<h3>{{ object.name}}</h3>


    {% for book in object.book_set.all %} <a href="{% url 'library:book_details' book.slug %}"><img src="{{ MEDIA_URL }}{{ book.image.url }}" style="width: 150px;height: 200px"> {{ book }}</a> <br>{% endfor %}<br>

    <span>Total Book:</span> {{ object.book_set.count }}


     <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}" style="color: #13b521">Previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" style="color: #13b521">Next</a>
            {% endif %}
        </span>
    </div>

{% endblock %}

templates/books/single_language_list.html
{% extends 'books/base.html' %}
{% block title %}<title>{{ object.language }}</title>{% endblock %}
{% block content %}

<h3>{{ object.language }}</h3>


    {% for book in object.book_set.all %} <a href="{% url 'library:book_details' book.slug %}"><img src="{{ MEDIA_URL }}{{ book.image.url }}" style="width: 150px;height: 200px"> {{ book }}</a> <br>{% endfor %}<br>

    Total Book: {{ object.book_set.count }}

{% endblock %}